In [2]:
# Add your imports here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
%matplotlib inline

In [3]:
persons = pd.read_csv("persons_occurences_day.csv").dropna()
persons = persons.sort_values(['Year', 'Month', 'Day', 'Count'], ascending=[True, True, True, False])
persons.Year = persons.Year.astype(int)
persons.Month = persons.Month.astype(int)
persons.Day = persons.Day.astype(int)
persons['Date'] = persons.apply(lambda row: datetime(row['Year'], row['Month'], row['Day']), axis=1)
persons = persons.drop(columns = ['Day', 'Month', 'Year'])
persons = persons.set_index('Date')

In [4]:
persons

                           Actor  Count
Date
2015-02-18           los angeles    112
2015-02-18     robert van winkle     83
2015-02-18       moammar gadhafi     80
2015-02-18           steve deuel     79
2015-02-18            tammy khan     78
2015-02-18  abu bakr al-baghdadi     78
2015-02-18         omar al-sinki     78
2015-02-18       turki al-binali     77
2015-02-18             abu talha     76
2015-02-18            ras lanouf     76
2015-02-18  abu al-baraa el-azdi     75
2015-02-18        khalifa hifter     74
2015-02-18         reem el-breki     73
2015-02-18    cory milsap-harris     67
2015-02-18          todd spitler     64
2015-02-18           paul kranke     64
2015-02-18             tom kloza     63
2015-02-18        brittney davis     63
2015-02-18      erika monterroza     62
2015-02-18          alicia chang     61
2015-02-18     christopher weber     61
2015-02-18          john antczak     61
2015-02-18            van winkle     52
2015-02-18           tony abbott     51
2015-02-18          indian ocean     40
2015-02-18      arrmanatha nasir     34
2015-02-18           andrew chan     34
2015-02-18      myuran sukumaran     34
2015-02-18             alan nash     31
2015-02-18    kelley gillenwater     30
...                          ...    ...
2017-11-23          maura healey     60
2017-11-23          janet yellen     59
2017-11-23          trace adkins     59
2017-11-23        fatou bensouda     58
2017-11-23      malcolm turnbull     57
2017-11-23        jay weatherill     57
2017-11-23      harvey weinstein     57
2017-11-23             donald jr     56
2017-11-23            al franken     56
2017-11-23        curtis sagmoen     56
2017-11-23       min aung hlaing     56
2017-11-23           arva dorsey     54
2017-11-23            jacob zuma     53
2017-11-23        mukhisa kituyi     51
2017-11-23             las vegas     51
2017-11-23           craig clark     50
2017-11-23          jose pereira     50
2017-11-23          rateb jabour     46
2017-11-23           santa claus     46
2017-11-23         joao lourenco     46
2017-11-23         masafer yatta     46
2017-11-23        vladimir putin     45
2017-11-23         joseph kabila     45
2017-11-23        tiago dionisio     44
2017-11-23           aung hlaing     44
2017-11-23         markus weimer     44
2017-11-23          dan kaminsky     43
2017-11-23          nicola maxey     43
2017-11-23          bill clinton     43
2017-11-23         kyle flaherty     43

[101153 rows x 2 columns]

In [19]:
persons[persons.Actor.str.startswith('kim jong')]

                   Actor  Count
Date
2015-08-09  kim jong suk    118
2016-01-06      kim jong    512
2016-09-09      kim jong    226
2016-11-27      kim jong    127
2017-02-16  kim jong nam    258
2017-02-16  kim jong-nam    254
2017-02-18  kim jong nam    208
2017-02-18  kim jong-nam    175
2017-02-19  kim jong nam    209
2017-02-19  kim jong-nam    192
2017-02-20  kim jong nam    951
2017-02-20  kim jong-nam    398
2017-02-21  kim jong nam    352
2017-02-21  kim jong-nam    226
2017-02-22  kim jong nam    348
2017-02-22  kim jong-nam    224
2017-02-23  kim jong nam    254
2017-02-24  kim jong nam    989
2017-02-24  kim jong-nam    275
2017-02-25  kim jong nam   1342
2017-02-25  kim jong-nam    399
2017-02-25      kim jong    203
2017-02-26  kim jong nam    744
2017-02-26  kim jong-nam    200
2017-02-27  kim jong nam    281
2017-02-28  kim jong nam    501
2017-02-28  kim jong-nam    194
2017-03-01  kim jong nam    283
2017-03-02  kim jong nam    858
2017-03-03  kim jong nam    874
2017-03-04  kim jong nam    498
2017-03-04  kim jong-nam    236
2017-03-04      kim jong    144
2017-03-05  kim jong-nam    247
2017-03-06  kim jong-nam    332
2017-03-06  kim jong nam    291
2017-03-06      kim jong    156
2017-03-07  kim jong nam    187
2017-03-07  kim jong-nam    162
2017-03-08  kim jong nam    173
2017-03-14  kim jong nam    409
2017-04-13  kim jong nam    187
2017-04-16      kim jong     86
2017-05-01      kim jong    167
2017-07-06      kim jong    126
2017-08-06      kim jong    110
2017-08-07      kim jong    133
2017-08-15      kim jong    151
2017-09-15      kim jong    186
2017-09-23      kim jong    188